<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUn8rvnx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUn8rvnx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUn8rvnx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUn8rvnx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUn8rvnx\appProdProjectContainer(array(
    'container.build_hash' => 'Un8rvnx',
    'container.build_id' => 'b8dc5486',
    'container.build_time' => 1701709084,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUn8rvnx');
